Insert Into recipe (category, slug, title, image, description, calories, protein, fat, gluten_free, egg_free)
Values
  ('entrée', 'herb-roasted-chicken', 'Herb Roasted Chicken', 'herb-roasted-chicken', '', 0, 0, 0, true, false),
  ('entrée', 'spinach-filo-puffs', 'Spinach Filo Puffs', 'spinach-filo-puffs', '', 0, 0, 0, true, false),
  ('entrée', 'beef-pot-pie', 'Beef Pot Pie', 'beef-pot-pie', '', 0, 0, 0, false, false),
  ('entrée', 'creamy-pesto-pasta', 'Creamy Pesto Pasta', 'creamy-pesto-pasta', '', 0, 0, 0, true, false),
  ('entrée', 'cauliflower-pizza-crust', 'Cauliflower Pizza Crust', 'cauliflower-pizza-crust', '', 0, 0, 0, true, false),
  ('entrée', 'quinoa-stuffed-pork-tenderloin', 'Quinoa Stuffed Pork Tenderloin', 'quinoa-stuffed-pork-tenderloin', '', 0, 0, 0, true, false),
  ('appetizer', 'grilled-portobello-mushrooms', 'Grilled Portobello Mushrooms', 'grilled-portobello-mushrooms', '', 0, 0, 0, true, false),
  ('appetizer', 'asparagus-wrapped-in-crisp-prosciutto', 'Asparagus Wrapped in Crisp Prosciutto', 'asparagus-wrapped-in-crisp-prosciutto', '', 0, 0, 0, true, false),
  ('appetizer', 'basil-shrimp', 'Basil Shrimp', 'basil-shrimp', '', 0, 0, 0, true, false),
  ('appetizer', 'guacamole', 'Guacamole', 'guacamole', '', 0, 0, 0, true, false),
  ('appetizer', 'hummus', 'Hummus', 'hummus', '', 0, 0, 0, true, false),
  ('appetizer', 'watermelon-fire-and-ice-salsa', 'Watermelon Fire and Ice Salsa', 'watermelon-fire-and-ice-salsa', '', 0, 0, 0, true, false),
  ('dessert', 'cheesecake-cupcakes', 'Cheesecake Cupcakes', 'cheesecake-cupcakes', '', 0, 0, 0, true, false),
  ('dessert', 'flourless-chocolate-cake', 'Flourless Chocolate Cake', 'flourless-chocolate-cake', '', 0, 0, 0, true, false),
  ('dessert', 'meringue-crust', 'Meringue Crust', 'meringue-crust', '', 0, 0, 0, true, false),
  ('dessert', 'layer-bars', 'Layer Bars', 'layer-bars', '', 0, 0, 0, true, false),
  ('dessert', 'peanut-butter-cookies', 'Peanut Butter Cookies', 'peanut-butter-cookies', '', 0, 0, 0, true, false),
  ('dessert', 'strawberry-soup', 'Strawberry Soup', 'strawberry-soup', '', 0, 0, 0, true, false),
  ('cocktail', 'frozen-pumpkin-spice-cocktail', 'Frozen Pumpkin Spice Cocktail', 'frozen-pumpkin-spice-cocktail', '', 0, 0, 0, true, false),
  ('cocktail', 'the-real-mojito', 'The Real Mojito', 'the-real-mojito', '', 0, 0, 0, true, false),
  ('cocktail', 'wild-river-bloody-mary-mix', 'Wild River Bloody Mary Mix', 'wild-river-bloody-mary-mix', '', 0, 0, 0, true, false),
  ('cocktail', 'party-mimosa', 'Party Mimosa', 'party-mimosa', '', 0, 0, 0, true, false),
  ('cocktail', 'italian-amaretto-margaritas', 'Italian Amaretto Margaritas', 'italian-amaretto-margaritas', '', 0, 0, 0, true, false),
  ('cocktail', 'hot-buttered-rum-batter', 'Hot Buttered Rum Batter', 'hot-buttered-rum-batter', '', 0, 0, 0, true, false);
